### PR TITLE
[Woptim] Update software stack for AMD architecture. Introduce rocm 5.7.1

### PR DESCRIPTION
**Pull request by adrienbernede**

### CODE REVIEW

**Comment by adayton1** [comment]
@adrienbernede, this may have broken Umpire on Tioga (with a develop version of radiuss-spack-configs):

==> Error: concretization failed for the following reasons:
   1. No valid version for 'umpire' compiler 'cce' satisfies '@16.0.0'
[exe: /dev/shm/tioga30-1640271/spack/bin/spack dev-build --fresh --quiet -d /usr/WS2/umdev/gitlab-runner/umdev/builds/9YsVm9VV/002/gitlab/radiuss/Umpire -u initconfig 'umpire@develop~shared +fortran tests=basic %cce@16.0.0']
==> Error: concretization failed for the following reasons:
   1. No valid version for 'umpire' compiler 'cce' satisfies '@16.0.0'

**Comment by adrienbernede** [comment]
@adayton1 It is true that this change is not transparent. This is why there is a dedicated PR in Umpire: https://github.com/LLNL/Umpire/pull/864
I wasn’t expecting someone to try to update to radiuss-spack-configs@main before the above is merged.

I chose to move from cce@16.0.0 to cce@16.0.1 instead of maintaining both.
What you need to do is to look for cce@16.0.0 in the local CI jobs (.gitlab/jobs/[tioga/corona].yml) and change it for cce@16.0.1.

**Comment by adrienbernede** [comment]
Now, if you update radiuss-spack-configs to `main`, please beware of the change in the fmt requirement in the Umpire package. I had to specify the cxx standard for intel compiler when using a recent enough Spack that would trigger the build of fmt@10.1.0+.

**Comment by adayton1** [comment]
Thanks, @adrienbernede. I see now that umpire was explicitly overriding the cce@16.0.0 job, so I'll update that. The branch I am working on is the one that starts using the fmt requirement in Umpire. I had to make a patch for fmt to work with another compiler, so there's another update in radiuss-spack-configs that brings in fmt with some changes.

**Pull request merged**
