### PR TITLE
Added versions of various compilers and CUDA for blueos and toss4

### PR DESCRIPTION
**Pull request by rhornung67**
To update and expand coverage in Gitlab CI testing.

### CODE REVIEW

**Review by mcfadden8 — APPROVED** [review]
Looks good to me @rhornung67.  Is there any way we can somehow flag the minimal set we should be building with in our CI?  Maybe two or three classes of compilers?

- Oldest: The oldest version run by CI
- Current: Version being used by most build systems (Mike)
- Newest: The newest version run by CI

Three compiler versions are likely too many, but it would be good I think to allow our CI to automatically test with at minimum the compiler version considered to be the current one.

**Comment by rhornung67** [comment]
@mcfadden8 I agree with what you are saying. I believe the specs in here are basically a dumping ground for everything someone wants to/has had to try.  Somehow doing what you suggest would help make multiple projects have a consistent tested compiler support story. Not sure how to do that.

On a related note, it would be good to have a systematic way to add new specs here routinely when new compilers are installed on LC machines. Perhaps folks who contribute to this could take on that responsibility on a revolving basis?

**Comment by mcfadden8** [comment]
I can think of two options for doing this and neither are really ideal.  

- We could consider duplicating an entire spec for each alias and just keep all of the aliases grouped in one place in the file so they could easily be updated.
- We could consider creating something in uberenv (hand waving) like a configuration file that would contain the aliases.  The configuration file could be maintained in RADIUSS
-

**Comment by rhornung67** [comment]
@adrienbernede david and marty think is ready to merge. please review and approve if you agree, or make comments if you want me to make changes. thank you.

**Comment by adrienbernede** [comment]
@rhornung67 @mcfadden8
I was not available and I think you were right to merge this.

**Pull request merged**
