### PR TITLE
Add rocprim external

### PR DESCRIPTION
**Pull request by davidbeckingsale**

### CODE REVIEW

**Comment by cyrush** [comment]
Related question I have.

For our cmake build systems we want to provide the root of the rocm install(`ROCM_PATH`).

But spack does not have that.  It has many rocm related packages. 

It seems in this cases, `rocmprim` points to `ROCM_PATH`, I have also seen `rocminfo` point there (but most packages don't depend on `rocminfo`).  

It seems these things could be layout out in many ways. 

Whats the best way to get this info from spack w/o twisting ourselves into knots?  Does `rocmprim` do the trick? Is there something I missed from ROCmPackage that provides this info and I just missed it?

**Comment by rhornung67** [comment]
@cyrush I think @trws is working up a solution for this issue.

**Comment by trws** [comment]
@cyrush, there are actually two ways to solve this depending on what you want.

1. the spack way: Spack ensures that *all* the packages that provide cmake config files are added to the prefix path, so when building in that environment the `ROCM_PATH` should be unnecessary.  I say *should* because some of the amd comfig logic is broken, which we're adding workarounds for and submitting as bugs.
2. The FHS way: to get everything to work as though it were a normal installation with a ROCM_PATH that actually works, have spack create a view, either with `spack view` or by using an environment, then point cmake builds to that as ROCM_PATH.  This takes one out of spack, but will work for things where the multi-path stuff is broken without workarounds.

**Comment by cyrush** [comment]
My goals:

For spack: is to have spack configs that work on our HPC systems at LLNL and ORNL & to have a config for a ROCm ubuntu container that is using AMD system installs (apt-get installed) for the ROCm stack.  

For cmake:

I would like this to be as simple as possible -- here is ROCM,  use this compiler. 

I have no idea how much of the rocm stack is a la carte. I suspect even if a la carte parts are possible, that simple would want some agreed upon core set of the packages b/c anything is is going to be to mentally exhausting to support. 

-- 

I was hitting issues with my ROCm container. 

I can build just fine in there outside of spack. 

But even when I figured out what cmake options work, I don't see how to translate that into spack configs. I can specify a bunch of rocm external packages, I don't want to hand everyone of those things to cmake inside of spack, that's bananas. 






I start with the container, and that is where I was seeing issues.

**Comment by trws** [comment]
Why do you specifically want to build in spack in a container with rocm installed outside of spack? If that's a requirement, we'll get there, but there are likely to be rough edges for a while.  If every rocm package is specified as an external, and yes I mean *all* of them, then it should work without passing anything to cmake inside the spack package at all.  All their cmake paths should show up in the prefix paths and it should just work, that's how things worked before.  Problem now is AMD redid something and we're seeing more breakage because of their badly botched rework of path handling in some of the packages, especially the hip package itself.

**Comment by cyrush** [comment]
Mainly b/c we are actually going to run we won't have ROCm installed by spack.

But we do want to use spack to build our TPLs.

That is how it will work on the HPC platforms - I am not going to ask spack to build ROCm, I will be using system installs and need spack to understand them.

**Comment by trws** [comment]
Fair enough, it certainly should work, especially with externals set up appropriately.  The trick is that spack sets things up per-package, and AMD decomposed ROCM into a great deal of packages, both in spack and in RPMs and debs.  As long as they're all tied in, it should just work, and that's where we're trying to get to. This PR is a good example of the problem though, ROCPrim used to come in by default with something else we already had in externals, but got re-packaged and no longer comes in that way.  It broke our spack package as well.  Hopefully once we get over the bumps in the next couple of ROCM releases this will all stabilize a bit more and get us where we need to be.

**Comment by davidbeckingsale** [comment]
I'm going to go ahead and merge this since it's needed for https://github.com/LLNL/RAJA/pull/1284

**Pull request merged**
