### PR TITLE
Add new set of compilers selected for CI

### PR DESCRIPTION
**Pull request by davidbeckingsale**

### CODE REVIEW

**Comment by adrienbernede** [comment]
@davidbeckingsale Is there something to keep from this PR ? (oneapi ?).

**Comment by davidbeckingsale** [comment]
That could be useful, but I think in general this has been made redundant by the shared CI stuff.

**Comment by adrienbernede** [comment]
How so ? I guess you are talking about the gcc toolchain flags.
That raises an interesting question though: Wouldn’t we be better off with the gcc toolchain defined here ?

**Comment by adrienbernede** [comment]
Oh, yes you mean redundant with the other PR. Got it.

**Comment by rhornung67** [comment]
@davidbeckingsale do you still want this PR? I recently updated the specs to include almost everything that is available on LC machines https://github.com/LLNL/radiuss-spack-configs/pull/47  I will be doing another PR soon to include anything missing from this list: https://github.com/LLNL/radiuss-shared-ci/issues/15

**Comment by davidbeckingsale** [comment]
> @davidbeckingsale do you still want this PR? I recently updated the specs to include almost everything that is available on LC machines #47 I will be doing another PR soon to include anything missing from this list: [LLNL/radiuss-shared-ci#15](https://github.com/LLNL/radiuss-shared-ci/issues/15)

Yup this is outdated, I will close it.

**Pull request closed without merging**
